### PR TITLE
Add human-readable manifest.txt to nano.jar

### PR DESCRIPTION
**Pull request by jdh8**
I have test on Firefox 38 on Linux, our getRes returns 2e-7. This is decent for a builtin timer.

For more information see https://developer.mozilla.org/en-US/docs/Web/API/Performance/now.

I also try to add manifest.txt to nano.jar again, repacking the jar instead of direct joining manifest.txt.

    jar cf nano.jar manifest.txt nano.class

### CODE REVIEW

**Comment by jdalton** [comment]
We've removed the `performance` timer at one time. I need to dig into why. What's the manifest.txt thing about?

**Comment by jdalton** [comment]
See https://github.com/bestiejs/benchmark.js/commit/a9f397e5cd775a50e2ea49689f43088a2dfcc6f3#commitcomment-5431323 for why we aren't including `performance.now`.

**Comment by jdh8** [comment]
It is [JAR File Manifest Attributes for Security][manifest], which is about the permissions of the Java applet.  If it is unset, user is prompted to run the applet or not.

The manifest I set is:

    Permissions: sandbox
    Codebase: *
    Application-Name: nano

This declares that the application `nano` only needs `sandbox` permissions, anywhere (`Codebase: *`)

We successfully set the manifest in binary form, as in META-INF/MANIFEST.MF in nano.jar.  However, its source code of the manifest (as mentioned above) was not committed.  I add the source to ensure that we can regenerate nano.jar and to conform free software license.

[manifest]: http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/manifest.html

**Comment by jdalton** [comment]
If you can revert the `performance.now` stuff and keep the manifest stuff I think this PR is good to go.

**Comment by jdh8** [comment]
In the [MDN page abot performance.now][now] I mentioned before, they say

> Windows version of Chrome 20 through 33, at the time of this writing, returns performance.now() only to millisecond precision.

Is this the case that performance.now() returns an integer? :(

[now]: https://developer.mozilla.org/en-US/docs/Web/API/Performance/now

**Comment by jdalton** [comment]
I'm not wanting to revisit `performance.now` at the moment.

**Comment by jdalton** [comment]
Closing since we've removed the nano.jar.

**Pull request closed without merging**
