### PR TITLE
Fixed сritical Mann-Whitney U-values for 95% confidence

### PR DESCRIPTION
**Pull request by miripiruni**
Fix for #116 

Looks like tTable contains values for 97.5% confidence. But uTable — 95%. I changed tTable values.

### CODE REVIEW

**Comment by miripiruni** [comment]
@jdalton rebased from master.

**Comment by miripiruni** [comment]
@jdalton rebased from master.

**Comment by miripiruni** [comment]
And why it’s enhancement? I think, it’s bug.

**Comment by miripiruni** [comment]
@jdalton ping?

**Comment by jdalton** [comment]
Hey @miripiruni!

I'll dig into this when I can. Until then relax a bit.

**Comment by miripiruni** [comment]
Thank you, @jdalton!

**Comment by GerHobbelt** [comment]
## Analysis

The original values for the t-table are correct, as the benchmark tests are of the type called 'two-sided-tail tests': compared to the sample (i.e. the tests run and measured) the 'true' performance of the tested code may be either slower or faster than the test results. This is better explained in these pages:

- https://www.cliffsnotes.com/study-guides/statistics/principles-of-testing/one-and-twotailed-tests
- https://en.wikipedia.org/wiki/One-_and_two-tailed_tests

Hence, following the guidance in

- https://en.wikipedia.org/wiki/Student%27s_t-distribution

one can conclude that the values for the t-table published in the next page are for ONE-SIDED rather than two-sided tails:

- http://www.itl.nist.gov/div898/handbook/eda/section3/eda3672.htm (WARNING: the table listed there is for ONE-SIDED regions!)

and those numbers match up with the one-sided p=0.05 (95%) column in the above-mentioned wikipedia article, while *we* need the 95% column for the two-sided type, which happens to equal the 97.5% column for the one-sided type.

---

If this doesn't make sense to you, I suggest you read *all* referenced pages. I had to do so too (plus grokking a few more pages on the relevant statistics) before I understood *why* it is like it is, and why this pullreq SHOULD NOT be applied.

**Comment by jdalton** [comment]
Thanks @GerHobbelt!

Sounds very familiar from when I implemented it in 2010. The extra context is a good thing!

**Pull request closed without merging**
