### PR TITLE
Load Lo-Dash from correct location

### PR DESCRIPTION
**Pull request by paldepind**
The test won't run of the master branch:
```
$  node test/test
module.js:338
    throw err;
          ^
Error: Cannot find module '../node_modules/qunitjs/qunit/qunit.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/simon/projects/benchmark.js/test/test.js:26:13)
    at Object.<anonymous> (/home/simon/projects/benchmark.js/test/test.js:1293:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
It appears that the file name of Lo-Dash has been changed. This commit follows the change and makes the tests run fine.

### CODE REVIEW

**Comment by d10** [comment]
This issue is not with lodash, it’s with the QUnit module: `Cannot find module '../node_modules/qunitjs/qunit/qunit.js'`.

If your fix is included, [lodash would then fail to load](https://travis-ci.org/bestiejs/benchmark.js/jobs/53033100#L151).

**Comment by paldepind** [comment]
Sorry, I accidentally pasted the wrong error message from before I did "npm install". The actual error message was definitely about Lo Dash and the changes in this pull request was necessary in order to run the tests.

**Comment by d10** [comment]
Well then, I’m not too sure what’s the issue. The Travis runs are still failing though.

**Comment by jdalton** [comment]
Yap, thanks you can see lodash loaded from a few places in the source. It was before we settled on the paths for v3.

**Pull request merged**
