### PR TITLE
Fix loading of Browserscope visualization

### PR DESCRIPTION
**Pull request by mathiasbynens**
Fixes https://github.com/jsperf/jsperf.com/issues/235.
Ref. https://github.com/jsperf/jsperf.com/pull/364.

Thanks to @danez!

### CODE REVIEW

**Comment by jdalton** [comment]
YES! 🎉

**Comment by mathiasbynens** [comment]
Would you mind tagging and publishing a new release so jsPerf can be updated?

**Comment by jdalton** [comment]
Will do!

**Comment by jdalton** [comment]
Done!

**Pull request merged**
