### PR TITLE
remove setting user agent in jsperf example

### PR DESCRIPTION
**Pull request by maxbeatty**
using a server-side parser in https://github.com/jsperf/jsperf.com/pull/144 so this line won't be used anymore

### CODE REVIEW

**Comment by jdalton** [comment]
I'm still a little bit confused as to why this sample holds any significance for the site. It shouldn't.

**Comment by jdalton** [comment]
Related to https://github.com/bestiejs/benchmark.js/pull/151#issuecomment-233860387.

**Comment by mathiasbynens** [comment]
@jdalton The build script for https://github.com/jsperf/benchmark.js-wrapper fetches [a tagged version](https://github.com/jsperf/benchmark.js-wrapper/blob/152abb17f560b797bcb96caa6cca5a8cbb7885ce/gulpfile.js#L24) of `examples/jsperf/ui.js` (as well as lodash and Benchmark.js itself) and combines that into the `test.js` file that is/will be used on jsperf.com.

**Comment by jdalton** [comment]
Shouldn't the site keep its own ui.js?
Pulling a critical part of jsperf from a lib sample seems out of place.

**Comment by mathiasbynens** [comment]
I guess the sample could be moved to a separate repository (e.g. `jsperf/ui.js`), but for now we’ve just ported the old build script.

**Pull request merged**
